name: Pydemic CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [master]

jobs:
  suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with pycodestyle
        run: |
          docker-compose run pydemic-ui pycodestyle
      - name: Test with pytest
        run: |
          pip install pytest-cov
          docker-compose run pydemic-ui pytest --cov=./
      - name: Code Coverage
        run: |
          sudo pip install codecov
          codecov
