
name: Pydemic CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cp assets/locale.gen /etc/locale.gen
        locale-gen
        python -m pip install --upgrade pip
        pip install flit pycodestyle pytest
        flit install
        pip uninstall -y pydemic-models
        pip install git+https://github.com/GCES-Pydemic/pydemic.git
        inv i18n
        
    - name: Lint with pycodestyle
      run: |
        pycodestyle
    - name: Test with pytest
      run: |
        pytest